config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'homes/top'
  get 'home/about' => "homes#about"

  root to: "homes#top"

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
 }


 delete '/books/:book_id/favorites', to: 'favorites#destroy' ,as: :favorite_delete

 resources :users, only: [:index, :show, :edit, :update] do
  resource :relationships, only: [:create, :destroy] do
    member do
      get :follows
      get :followers
    end
  end
end


resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
  resources :favorites, only: [:create, :destory]
  resource :book_comments, only: [:create, :destroy]
end

resource :search, only: [:serch_user, :search_book] do
  collection do
    get 'search'
    get 'search_user'
    get 'search_book'
  end
end

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :book_comments
	has_many :favorites, dependent: :destroy
	validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }

    def favorite_user(user_id ,book_id)
    	Favorite.find_by(user_id: user_id, book_id: book_id)
    end

	def self.search_start(search)
	  Book.where(['title LIKE(?)', "#{search}%"])
	end

	def self.search_back(search)
	  Book.where(['title LIKE(?)', "%#{search}"])
	end

	def self.search_part(search)
	  Book.where(['title LIKE(?)', "%#{search}%"])
	end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :ensure_current_user, only: [:edit, :update]

	def ensure_current_user
		if user_signed_in?
	    	book = Book.find(params[:id])
	    	if current_user.id !=  book.user_id
	      		redirect_to books_path
	    	end
	    end
  	end

	def index
		if user_signed_in?
			@book = Book.new
			@books = Book.all
		else
			redirect_to new_user_session_path
		end
	end

	def show
		if user_signed_in?
			@book = Book.find(params[:id])
			@user = User.find(@book.user_id)
			@book_comment = BookComment.new
			@book_comments = BookComment.where(book_id: @book.id)
		else
			redirect_to new_user_session_path
		end
	end

	def create
		book = Book.new(book_params)
		book.user_id = current_user.id
		if book.save
		   redirect_to book_path(book.id), notice: 'Book was successfully created.'
		else
			@user = User.find(current_user.id)
			@book = book
			@books = Book.all
			render action: :index
		end
	end

	def edit
		if user_signed_in?
			@book = Book.find(params[:id])
		else
			redirect_to new_user_session_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
		else
			render action: :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end


	private
    def book_params
        params.require(:book).permit(:title, :body)
    end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<body>

	<%= render 'layouts/header' %>

	<div class="container" style="margin-top: 60px;">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
				<h1>Editing Book</h1>
			</div>

			<% if @book.errors.any? %>
				<h2 style="color: red;"><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
				<% @book.errors.full_messages.each do |msg| %>
					<li style="color: red;"><%= msg %></li>
				<% end %>
			<% end %>

			<%= form_for(@book) do |f| %>

				<div class="row">
					<div class="title col-lg-6 col-lg-offset-3">
						<p><strong>Title </strong></p>
					</div>
					<div class="col-lg-6 col-lg-offset-3">
						<%= f.text_field :title %>
					</div>
				</div>
				<div class="row">
					<div class="opinion col-lg-6 col-lg-offset-3">
						<p><strong>Opinion</strong></p>
					</div>
					<div class="col-lg-6 col-lg-offset-3">
						<%= f.text_area :body, class: "book-edit-form" %>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6 col-lg-offset-3">
						<%= f.submit "Update Book", class:"submit btn btn-primary btn-block" %>
					</div>
				</div>
			<% end %>
		</div>

		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
				<%= link_to "Show", book_path(@book) %>
				|
				<%= link_to "Back", books_path %>
			</div>
		</div>

	</div>



	<%= render 'layouts/footer' %>


</body>

app/views/books/index.html.erb
<body>

<%= render 'layouts/header' %>

<%= render 'layouts/search' %>

<div class="container">
	<div class="row">

		<% if @book.errors.any? %>
			<h2 style="color: red;"><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
			<% @book.errors.full_messages.each do |msg| %>
				<li style="color: red;"><%= msg %></li>
			<% end %>
		<% end %>

		<%= render 'layouts/sidebar',user: current_user, book: @book %>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<thead>
					<th colspan="1"></th> <th>Title</th> <th>Opinion</th>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', fallback: "no_image.jpg", size:'50x50' %>
                  			<% end %>
							</td>
							<td><%= link_to book.title,book_path(book.id) %></td>
							<td><%= book.body %></td>

							<% if book.favorite_user(current_user.id, book.id) %>
								<td><%= link_to book.favo_count.to_i, favorite_delete_path(book), method: "delete", class: "glyphicon glyphicon-heart" %></td>
							<% else %>
								<td><%= link_to book.favo_count.to_i, book_favorites_path(book), method: "post", class: "glyphicon glyphicon-heart-empty" %></td>
							<% end %>

							<td>コメント数：<%= book.book_comments_count.to_i %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>

	</div>

</div>

	<%= render 'layouts/footer' %>


</body>

app/views/books/show.html.erb
<body>

	<%= render 'layouts/header' %>

	<div class="container" style="margin-top: 70px;">
		<div class="row">

		<p id="notice" style="color: green;"> <!-- bookのサクセスメッセージ -->
			<%= notice %>
		</p>

			<%= render 'layouts/sidebar', user: current_user, book: @book %>

			<div class="col-xs-9">
				<h2>Book detail</h2>
				<table class="table">
					<tbody>
							<tr>
								<td>
								    <%= link_to user_path(@book.user) do %>
								    <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format:'jpeg', fallback: "no_image.jpg", size:'50x50' %>
									<% end %>
									<br>
									<%= link_to @user.name, user_path(@book.user) %>
								</td>
								<td><%= link_to @book.title,book_path(@book.id) %></td>
								<td><%= @book.body %></td>

								<% if @book.favorite_user(current_user.id, @book.id) %>
									<td><%= link_to @book.favo_count.to_i, favorite_delete_path(@book), method: "delete", class: "glyphicon glyphicon-heart" %></td>
								<% else %>
									<td><%= link_to @book.favo_count.to_i, book_favorites_path(@book), method: "post", class: "glyphicon glyphicon-heart-empty" %></td>
								<% end %>

								<td>コメント数：<%= @book.book_comments_count.to_i %></td>

								<% if current_user == @user %>
									<td><%= link_to 'Edit', edit_book_path(@book.id), {class: "btn btn-success"} %></td>
									<td class="btn btn-danger" style="margin-top: 10px;"><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
								<% end %>
							</tr>
					</tbody>
				</table>

				<table class="table">
					<tbody>
						<%= render 'book_comments/comment' %>
					</tbody>
				</table>

				<%= form_for [@book, @book_comment] do |f| %>
				<%= f.label :comment %><br>
				<%= f.text_area :comment %>
				<%= f.submit %>

				<% end %>

			</div>

		</div>

	</div>

	<%= render 'layouts/footer' %>
</body>