config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'homes/top'
  get 'home/about' => "homes#about"

  root to: "homes#top"

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
 }


 delete '/books/:book_id/favorites', to: 'favorites#destroy' ,as: :favorite_delete

 resources :users, only: [:index, :show, :edit, :update] do
  resource :relationships, only: [:create, :destroy] do
    member do
      get :follows
      get :followers
    end
  end
end


resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
  resources :favorites, only: [:create, :destory]
  resource :book_comments, only: [:create, :destroy]
end

resource :search, only: [:serch_user, :search_book] do
  collection do
    get 'search'
    get 'search_user'
    get 'search_book'
  end
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def search
		if params[:range] == 'user'
			match = params[:match]
			search = params[:search]
			if match == 'perfect'
				@users = User.where(name: search)
			elsif match == 'start'
				@users = User.all.search_start(search)
			elsif match == 'back'
				@users = User.all.search_back(search)
			elsif match == 'part'
				@users = User.all.search_part(search)
			end
			render :search_user
		else
			match = params[:match]
			search = params[:search]
			if match == 'perfect'
				@books = Book.where(title: search)
			elsif match == 'start'
				@books = Book.all.search_start(search)
			elsif match == 'back'
				@books = Book.all.search_back(search)
			elsif match == 'part'
				@books = Book.all.search_part(search)
			end
			render :search_book
		end
	end


	def search_user

	end

	def search_book

	end

end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searches/search_book.html.erb
<div class="col-xs-9">
			<h2>Search Books</h2>
			<table class="table">
				<thead>
					<th colspan="1"></th> <th>Title</th> <th>Opinion</th>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
							<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', fallback: "no_image.jpg", size:'50x50' %>
                  			<% end %>
							</td>
							<td><%= link_to book.title,book_path(book.id) %></td>
							<td><%= book.body %></td>

							<% if book.favorite_user(current_user.id, book.id) %>
								<td><%= link_to book.favo_count.to_i, favorite_delete_path(book), method: "delete", class: "glyphicon glyphicon-heart" %></td>
							<% else %>
								<td><%= link_to book.favo_count.to_i, book_favorites_path(book), method: "post", class: "glyphicon glyphicon-heart-empty" %></td>
							<% end %>

							<td>コメント数：<%= book.book_comments_count.to_i %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
</div>

<div class="col-xs-9">
<%= link_to ' Back ', books_path, class: "btn btn-success" %>
</div>

app/views/searches/search_user.html.erb
<div class="col-xs-9">
				<h2>Search Users</h2>
				<table class="table">
					<thead>
						<th>image</th> <th>name</th><th colspan="1"></th>
					</thead>

					<tbody>
					<% @users.each do |user| %>
							<tr>
								<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format:'jpeg', fallback: "no_image.jpg", size:'50x50' %></td>
								<td><%= user.name %></td>
								<td>フォロー数： <%= user.active_relationships.count %></td>
								<td>フォロワー数： <%= user.passive_relationships.count %></td>

					<% if current_user != user %>
						<% if user.followed_by?(current_user) %>
							<td><%= link_to 'フォロー中', user_relationships_path(user), method: "delete", class: "btn btn-primary" %></td>
						<% else %>
							<td><%= link_to ' フォロー ', user_relationships_path(user), method: "post", class: "btn btn-info" %></td>
						<% end %>
					<% else %>
						<td></td>
					<% end %>
					<td><%= link_to "Show", user_path(user) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div class="col-xs-9">
<%= link_to ' Back ', users_path, class: "btn btn-success" %>
</div>