config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'homes/top'
  get 'home/about' => "homes#about"

  root to: "homes#top"

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
 }


 delete '/books/:book_id/favorites', to: 'favorites#destroy' ,as: :favorite_delete

 resources :users, only: [:index, :show, :edit, :update] do
  resource :relationships, only: [:create, :destroy] do
    member do
      get :follows
      get :followers
    end
  end
end


resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
  resources :favorites, only: [:create, :destory]
  resource :book_comments, only: [:create, :destroy]
end

resource :search, only: [:serch_user, :search_book] do
  collection do
    get 'search'
    get 'search_user'
    get 'search_book'
  end
end

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<!-- ヘッダー部分 -->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-left">
      <span style="font-size:20px; color:white;">Bookers</span>
    </nav>

    <% if user_signed_in? %>
    <!-- サインイン済みの場合  -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to ' Home', user_path(current_user.id), {class: "glyphicon glyphicon-home home"} %></li>
        <li><%= link_to ' Users', users_path, {class: "glyphicon glyphicon-user users"} %></li>
        <li><%= link_to ' Books', books_path, {class: "glyphicon glyphicon-book books"} %></li>
        <li><%= link_to 'logout', destroy_user_session_path, {notice: 'You have updated user successfully.', method: :delete, class: "glyphicon glyphicon-log-out logout"} %></li>
      </ul>

    <% else %>
    <!-- サインインしていない場合 -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to ' Home', '/', {class: "glyphicon glyphicon-home home"} %></li>
        <li><%= link_to ' About', home_about_path, {class: "glyphicon glyphicon-link about"} %></li>
        <li><%= link_to ' sign up', new_user_registration_path, {class: "glyphicon glyphicon-edit sign_up"} %></li>
        <li><%= link_to ' login', new_user_session_path, {class: "glyphicon glyphicon-log-in sign_in"} %></li>
      </ul>

    <% end %>

  </div>

</header>

app/views/layouts/_search.html.erb
<div class="container col-xs-4 col-xs-offset-5" style="margin-top: 70px;">
	<%= form_tag(search_search_path, method: :get) do %>
		<%= text_field_tag :search %>
		<%= select_tag 'range', options_for_select({User: 'user', Book: 'book'}) %>
		<%= select_tag 'match', options_for_select({完全一致: 'perfect', 前方一致: 'start', 後方一致:'back', 部分一致:'part'}) %>
		<%= submit_tag 'Search', name: nil %>
	<% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-lg-3">
			<div class="col">
				<h2>User info</h2>
				<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format:'jpeg', class: "#", fallback: "no_image.jpg" %>
				<table class="table" style="font-weight: bold;">
					<tbody>
						<tr>
							<td>name</td>
							<td><%= user.name %></td>
						</tr>
						<tr>
							<td>introduction</td>
							<td><%= user.introduction %></td>
						</tr>
						<tr>
							<td>follows</td>
							<td><%= link_to user.active_relationships.count, follows_user_relationships_path(user) %></td>
						</tr>
						<tr>
							<td>followers</td>
							<td><%= link_to user.passive_relationships.count, followers_user_relationships_path(user) %></td>
						</tr>
					</tbody>
				</table>

				<% if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<td><%= link_to 'フォロー中', user_relationships_path(user), method: "delete", class: "btn btn-primary btn-block" %></td>
					<% else %>
						<td><%= link_to ' フォロー ', user_relationships_path(user), method: "post", class: "btn btn-info btn-block" %></td>
					<% end %>
				<% end %>

				<% if current_user == user %>
				<%= link_to '', edit_user_path(current_user.id), {class: "btn btn-default btn-block glyphicon glyphicon-wrench"} %>
				<% else %>
				<%= link_to '', user_path(current_user.id), {class: "btn btn-default btn-block glyphicon glyphicon-wrench"} %>
				<% end %>
			</div>

			<div class="col">
				<h2>New book</h2>
				<%= form_for(book) do |f| %>
					<p><strong>Title</strong></p>
					<%= f.text_field :title %>
					<p><strong>Opinion</strong></p>
					<%= f.text_area :body %>
					<%= f.submit "Create Book", class: "btn btn-block btn-primary"%>
				<% end %>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>